#!/usr/bin/perl

use warnings;
use strict;

use Wx;
use wxPerl::Constructors;

package MyApp;

use base 'Wx::App';

# --- No changes below here
#my $RunCommand = "~/.local/share/Steam/steamapps/common/Argentum\ Age/anura.sh --module=citadel --server=argentumage.gameplayer.club:23456";
my $RunCommand = "~/.local/share/Steam/steamapps/common/Argentum\ Age/anura.sh --module=citadel";

# Display list of games
sub DisplayGameList
{
}

# Run game...
sub RunGame
{
	# Get the arguments
	my $CurServer = $_[0];
	my $CurPort = $_[1];

	my $SystemCommand = "$RunCommand --server=$CurServer:$CurPort";

	PrintDebug("Running '$SystemCommand'\n");
	system($SystemCommand);
}

# About Popup
sub AboutPopup
{
}

# Main Init
sub OnInit
{
	my $self = shift;

	my $frame = wxPerl::Frame->new(undef, 'Argentum Age Games');
	$frame->SetMinSize([320,160]);
	my $sizer = Wx::BoxSizer->new(&Wx::wxVERTICAL);

	my $button = wxPerl::Button->new($frame, 'Games');
	$sizer->Add($button, 2, &Wx::wxEXPAND);
	my $buttonSync = wxPerl::Button->new($frame, 'Sync');
	$sizer->Add($buttonSync, 2, &Wx::wxEXPAND);
	my $buttonAbout = wxPerl::Button->new($frame, 'About');
	$sizer->Add($buttonAbout, 2, &Wx::wxEXPAND);
	my $button2 = wxPerl::Button->new($frame, 'Quit');
	$sizer->Add($button2, 1, &Wx::wxEXPAND);
	Wx::Event::EVT_BUTTON($button, -1, sub {
		my ($b, $evt) = @_;
		$b->SetLabel('Clicked');
		$b->Disable;
		DisplayGameList();
		$b->Enable;
	});
	Wx::Event::EVT_BUTTON($buttonAbout, -1, sub {
		my ($b, $evt) = @_;
		$b->SetLabel('Clicked');
		#$b->Disable;
	});
	Wx::Event::EVT_BUTTON($button2, -1, sub {
		&Wx::wxTheApp->ExitMainLoop;
	});

	$frame->SetSizer($sizer);
	$frame->Show;
}

MyApp->new->MainLoop;

exit 0;
